### ISSUE TITLE
Mobile App Dark Mode

### ISSUE THREAD

**Issue by deobald** [pariyatti/agga#4]
The original Sketch file is available in the [design](https://github.com/pariyatti/design) repo. Viba from Obvious.in and Sankalp (the original designer) have both volunteered to attempt a dark mode design, if they can find time.

**Comment by deobald** [comment]
@iamsankalp has created some sample colour options for us:

### Option 1: Full Black
<img width="375" alt="option_1" src="https://user-images.githubusercontent.com/20282/95291515-51c1d300-088d-11eb-97a8-7c7633f0dd0d.png">

### Option 2: Blue Tint
<img width="375" alt="option_2" src="https://user-images.githubusercontent.com/20282/95291511-4ff80f80-088d-11eb-8e58-34e00057c6b5.png">

### Option 3: Dark Brown
<img width="375" alt="option_3" src="https://user-images.githubusercontent.com/20282/95291503-4e2e4c00-088d-11eb-8ecd-158abccdbaf5.png">

Since I'm probably the only person in the group with a scleral buckle, macular degeneration, cataracts, no vitreous humor, and lens power approaching legally blind (-13.5), I'll go out on a limb and suggest I might be the best person to evaluate the accessibility of these colours. :wink: From an accessibility perspective, the blue tint is almost certainly the worst option. The dark brown, despite being lighter, __feels__ like it has a higher contrast than the blue tint. The full black option is far and wide the easiest to look at, though.

From an aesthetic perspective, I like the dark brown the best. I do find when I look at it my broken eyes wish it was darker. I'm not sure if that's an option, @iamsankalp ?

**Comment by iamsankalp** [comment]
Yep @deobald, Option 3 should be darker ideally. I'll get to try it out sooner.

**Comment by deobald** [comment]
@iamsankalp - I have checked with @brihas and he says that we can proceed with Option 1 (full black). You're welcome to experiment with a darker Option 3 if you are so inclined but otherwise the next step could be to apply the Option 1 colour scheme to one or two more complicated wireframes to ensure it doesn't conflict with the overall colour scheme (if you feel that's necessary). If it doesn't conflict, we can try applying the colour palette to the Flutter codebase. :)

**Comment by iamsankalp** [comment]
Hi! I got to try out 2 more screens and have mapped out a translation of colours from light to dark. Please check the images for reference.

I suggest we start with this and let me know if we encounter any issues in between.

<img width="400" alt="pariyatti_light to dark" src="https://user-images.githubusercontent.com/1756637/95829510-eaf05e00-0d53-11eb-8632-c9acdc4772e7.png">

<img width="375" alt="pariyatti_resources" src="https://user-images.githubusercontent.com/1756637/95829719-3d317f00-0d54-11eb-8842-00306ec5c39f.png">

<img width="375" alt="pariyatti_resource_detail" src="https://user-images.githubusercontent.com/1756637/95829703-360a7100-0d54-11eb-9f88-52e18fa35c18.png">

**Comment by deobald** [comment]
This is brilliant, @iamsankalp ! Thank you so much for your work on this. I'll close this issue and reference it from inside a mobile app issue for the dev team.

**Comment by VarunBarad** [comment]
@iamsankalp The complete black option 1 looks awesome 😍. Special thanks for providing the translation from light colors to dark 🙏
